//! The declaration surfaces (L12: "the declared surface is the public
//! contract").
//!
//! Four declaration tables name — verbatim, camelCase wire tags — everything
//! a consumer may rely on across the v2 boundary:
//!
//! | table | declares | spec |
//! |---|---|---|
//! | [`JOURNAL_ENTRIES`] | every `JournalWireEvent` variant (§C.2) | §C.2 |
//! | [`PROJECTION_KEYS`] | every projection key (§E.2, first version: 20) | §E.2 |
//! | [`HOST_EVENTS`] | every `HostEvent` variant (§D.5) | §D.5 |
//! | [`frames()`] | every stream kind + frame payload + end reason (§D.1) | §D.1 |
//!
//! plus the auxiliary call tables ([`CLIENT_CALLS`], [`CLIENT_NOTES`],
//! [`SERVER_CALLS`], [`SERVER_NOTES`]) for the §D.2–D.4 method vocabulary.
//!
//! # Single source, compiler-enforced (C3)
//!
//! Every table except [`PROJECTION_KEYS`] (a runtime key set, cross-checked
//! against the session-core registry by its own test) is generated by one
//! [`wire_surface!`] invocation per wire enum. Each invocation declares, in
//! one list, `(match pattern => wire tag ~ sample value)` per variant and
//! generates three artifacts from it:
//!
//! 1. the `pub const` declaration table,
//! 2. an **exhaustive** wire-tag match — a new enum variant that is not
//!    added to the list is a *compile error* (E0004), not a silently missed
//!    test,
//! 3. the ordered sample constructor the coverage harness walks.
//!
//! Table, tag function, and samples therefore cannot drift apart: they are
//! one list. The previous hand-maintained tables could and did drift —
//! `FRAMES` lacked `followSession` while `StreamKind` named FRAMES as its
//! declaring surface, and the scripted host events rode a fake
//! `FromServer::Response` envelope while production used `FromServer::Host`.
//!
//! Stability rules (L12): a name may be *added* at the tail of a group with
//! a protocol-epoch bump; it may never be renamed or removed outside a
//! deliberate spec revision. The `surface_*_complete` tests in
//! `tests/surface_coverage.rs` walk every list against serde: each sample
//! must serialize with exactly its declared tag and round-trip.

use crate::client::{ClientCall, ClientNote, ImageAttachment};
use crate::handshake::{HookKind, Initialize};
use crate::journal::{JournalWireEntry, JournalWireEvent, ModelRef, UsagePayload};
use crate::server::{ServerCall, ServerNote};
use crate::stream::{
    HostEvent, ProjectionsFrame, SessionSnapshot, StreamEndReason, StreamFrame, StreamKind,
};
use crate::wire::{ModelInfo, ThreadListItem};
use crate::{FromClient, FromServer};

/// Generates one declaration surface from a single per-variant list:
/// the const table, the exhaustive wire-tag match (the compile-time
/// drift gate), and the ordered sample constructor.
macro_rules! wire_surface {
    (
        $(#[$table_doc:meta])*
        table: $table:ident,
        $(#[$tag_doc:meta])*
        tags: $tag_fn:ident,
        $(#[$samples_doc:meta])*
        samples: $samples_fn:ident,
        ty: $ty:ty,
        [$( $pat:pat => $tag:literal ~ $sample:expr ),* $(,)?]
    ) => {
        $(#[$table_doc])*
        pub const $table: &[&str] = &[$($tag),*];

        $(#[$tag_doc])*
        pub fn $tag_fn(value: &$ty) -> &'static str {
            match value {
                $($pat => $tag),*
            }
        }

        $(#[$samples_doc])*
        pub fn $samples_fn() -> Vec<$ty> {
            vec![$( ($sample) ),*]
        }
    };
}

wire_surface! {
    /// The §C.2 entry vocabulary (wire tags). Grouped by the §C.2 table
    /// rows; order is stable, additions go at the tail of their group.
    table: JOURNAL_ENTRIES,
    /// Exhaustive wire-tag match for [`JournalWireEvent`] — the compile-time
    /// gate forcing every variant into [`JOURNAL_ENTRIES`] + samples.
    tags: journal_wire_tag,
    /// One representative per [`JOURNAL_ENTRIES`] tag, in table order.
    samples: journal_samples,
    ty: JournalWireEvent,
    [
        // transcript
        JournalWireEvent::Message { .. } => "message" ~ JournalWireEvent::Message {
            role: "user".into(),
            content: vec![serde_json::json!({"type": "text", "text": "hello"})],
            usage: None,
            origin_rpc: Some("rpc-1".into()),
        },
        JournalWireEvent::UiNote { .. } => "uiNote" ~ JournalWireEvent::UiNote {
            kind: "error".into(),
            data: serde_json::json!({"text": "oops"}),
        },
        JournalWireEvent::Custom { .. } => "custom" ~ JournalWireEvent::Custom {
            custom_type: "manox_ui_note".into(),
            data: serde_json::json!({"kind": "notice"}),
        },
        JournalWireEvent::CustomMessage { .. } => "customMessage" ~ JournalWireEvent::CustomMessage {
            custom_type: "extension".into(),
            content: vec![serde_json::json!({"type": "text", "text": "payload"})],
            display: true,
        },
        // lifecycle
        JournalWireEvent::TurnStart => "turnStart" ~ JournalWireEvent::TurnStart,
        JournalWireEvent::TurnFinish { .. } => "turnFinish" ~ JournalWireEvent::TurnFinish {
            cancelled: false,
            failed: true,
            stranded_steer_ids: vec!["st-1".into()],
        },
        JournalWireEvent::Stop { .. } => "stop" ~ JournalWireEvent::Stop {
            reason: Some("user stop".into()),
        },
        JournalWireEvent::Retry { .. } => "retry" ~ JournalWireEvent::Retry {
            attempt: 2,
            max_attempts: 5,
            delay_secs: 3,
            reason: "overloaded".into(),
        },
        JournalWireEvent::Error { .. } => "error" ~ JournalWireEvent::Error {
            message: "provider exploded".into(),
        },
        // streaming delta
        JournalWireEvent::AgentTextDelta { .. } => "agentTextDelta" ~ JournalWireEvent::AgentTextDelta { s: "to".into() },
        JournalWireEvent::AgentThinkingDelta { .. } => "agentThinkingDelta" ~ JournalWireEvent::AgentThinkingDelta { s: "k".into() },
        JournalWireEvent::ToolCall { .. } => "toolCall" ~ JournalWireEvent::ToolCall {
            call_id: "tc-1".into(),
            name: "Bash".into(),
            title: "run ls".into(),
            status: "running".into(),
            input: serde_json::json!({"command": "ls"}),
        },
        JournalWireEvent::ToolResult { .. } => "toolResult" ~ JournalWireEvent::ToolResult {
            call_id: "tc-1".into(),
            output: "a  b\n".into(),
            is_error: false,
        },
        JournalWireEvent::ToolOutputChunk { .. } => "toolOutputChunk" ~ JournalWireEvent::ToolOutputChunk {
            call_id: "tc-1".into(),
            chunk: "a".into(),
        },
        JournalWireEvent::SubagentChild { .. } => "subagentChild" ~ JournalWireEvent::SubagentChild {
            agent_id: "sub-1".into(),
            event: serde_json::json!({"type": "message"}),
        },
        JournalWireEvent::SubagentProgress { .. } => "subagentProgress" ~ JournalWireEvent::SubagentProgress {
            agent_id: "sub-1".into(),
            agent_type: "explore".into(),
            tool_uses: 4,
            latest_activity: Some("reading files".into()),
            status: "running".into(),
        },
        // state change
        JournalWireEvent::ModelChange { .. } => "modelChange" ~ JournalWireEvent::ModelChange {
            from: Some(ModelRef::new("anthropic-main/claude-sonnet-4")),
            to: ModelRef::new("DeepSeek-anthropic/deepseek-chat"),
        },
        JournalWireEvent::CwdChange { .. } => "cwdChange" ~ JournalWireEvent::CwdChange {
            path: "/new".into(),
        },
        JournalWireEvent::ProjectChange { .. } => "projectChange" ~ JournalWireEvent::ProjectChange {
            path: Some("/proj".into()),
        },
        JournalWireEvent::PermissionModeChange { .. } => "permissionModeChange" ~ JournalWireEvent::PermissionModeChange {
            mode: "accept-edit".into(),
        },
        JournalWireEvent::ReasoningEffortChange { .. } => "reasoningEffortChange" ~ JournalWireEvent::ReasoningEffortChange {
            effort: "high".into(),
        },
        JournalWireEvent::PlanModeChange { .. } => "planModeChange" ~ JournalWireEvent::PlanModeChange { enabled: true },
        JournalWireEvent::PlanUpdate { .. } => "planUpdate" ~ JournalWireEvent::PlanUpdate {
            snapshot: serde_json::json!({"body": "# plan"}),
        },
        JournalWireEvent::Goal { .. } => "goal" ~ JournalWireEvent::Goal {
            goal: Some(serde_json::json!({"objective": "ship v2", "budget": 10})),
        },
        JournalWireEvent::Title { .. } => "title" ~ JournalWireEvent::Title {
            title: "v2 migration".into(),
        },
        JournalWireEvent::BrowserSuites { .. } => "browserSuites" ~ JournalWireEvent::BrowserSuites {
            suites: vec!["web_explore".into()],
        },
        JournalWireEvent::BackgroundTask { .. } => "backgroundTask" ~ JournalWireEvent::BackgroundTask {
            snapshot: serde_json::json!({"tasks": []}),
        },
        JournalWireEvent::Approval { .. } => "approval" ~ JournalWireEvent::Approval {
            kind: "request".into(),
            auth_id: "auth-1".into(),
            tool_name: Some("Bash".into()),
            tool_call_id: Some("tc-1".into()),
            verdict: None,
            reason: None,
        },
        JournalWireEvent::PinnedArchived { .. } => "pinnedArchived" ~ JournalWireEvent::PinnedArchived {
            pinned: true,
            archived: false,
        },
        JournalWireEvent::ActiveToolsChange { .. } => "activeToolsChange" ~ JournalWireEvent::ActiveToolsChange {
            tools: vec!["Bash".into(), "Read".into()],
        },
        // compaction / tree
        JournalWireEvent::Compaction { .. } => "compaction" ~ JournalWireEvent::Compaction {
            summary: "…".into(),
            messages_compacted: 12,
            tokens_before: 40_000,
            retained_tail: vec![serde_json::json!({"role": "user"})],
            first_kept_entry_id: Some("e-30".into()),
        },
        JournalWireEvent::CompactionStarted { .. } => "compactionStarted" ~ JournalWireEvent::CompactionStarted {
            tokens_before: 40_000,
        },
        JournalWireEvent::BranchSummary { .. } => "branchSummary" ~ JournalWireEvent::BranchSummary {
            text: "fork note".into(),
        },
        JournalWireEvent::Label { .. } => "label" ~ JournalWireEvent::Label {
            label: "checkpoint".into(),
        },
        JournalWireEvent::SessionInfo { .. } => "sessionInfo" ~ JournalWireEvent::SessionInfo {
            data: serde_json::json!({"k": "v"}),
        },
        JournalWireEvent::Leaf { .. } => "leaf" ~ JournalWireEvent::Leaf {
            target_id: "e-12".into(),
        },
        // metrics
        JournalWireEvent::Metrics { .. } => "metrics" ~ JournalWireEvent::Metrics {
            kind: "cache_invalidation".into(),
            data: serde_json::json!({"reprocessedTokens": 12345}),
        },
    ]
}

/// The §E.2 projection key table (first version, 20 keys). Keys are wire
/// strings of `SessionSnapshot.projections` / `ProjectionsFrame.values`; the
/// fold sources are kernel-side (§E.1), so this table names the *values* the
/// client may read (L6: client never folds domain state itself). Not
/// macro-generated: keys are runtime strings owned by the session-core
/// registry, which cross-checks itself against this table by test.
pub const PROJECTION_KEYS: &[&str] = &[
    "title",
    "cwd",
    "project",
    "model",
    "permission_mode",
    "reasoning_effort",
    "plan_mode",
    "plan",
    "goal",
    "running",
    "has_interacted",
    "pinned",
    "archived",
    "depth",
    "branch",
    "browser_suites",
    "pending_auth",
    "background_tasks",
    "agent_label",
    "self_author",
];

wire_surface! {
    /// The §D.5 host-event vocabulary (wire tags).
    table: HOST_EVENTS,
    /// Exhaustive wire-tag match for [`HostEvent`] (compile-time gate).
    tags: host_wire_tag,
    /// One representative per [`HOST_EVENTS`] tag, in table order.
    samples: host_samples,
    ty: HostEvent,
    [
        HostEvent::Ready { .. } => "ready" ~ HostEvent::Ready { epoch: 2 },
        HostEvent::Models { .. } => "models" ~ HostEvent::Models {
            models: vec![ModelInfo {
                id: "deepseek-chat".into(),
                name: "DeepSeek Chat".into(),
                provider: "DeepSeek-anthropic".into(),
                provider_name: Some("DeepSeek".into()),
                api: "anthropic".into(),
                context_window: 131_072,
                max_tokens: Some(8_192),
            }],
        },
        HostEvent::Commands { .. } => "commands" ~ HostEvent::Commands {
            commands: serde_json::json!([{"name": "/compact"}]),
        },
        HostEvent::ThreadsUpdated { .. } => "threadsUpdated" ~ HostEvent::ThreadsUpdated {
            threads: vec![thread_stub()],
        },
        HostEvent::SessionStatus { .. } => "sessionStatus" ~ HostEvent::SessionStatus {
            session_id: "s1".into(),
            running: Some(true),
            errored: Some(false),
            unread: Some(true),
            pending_auth: Some(false),
            pending_plan: None,
            background_work: Some(false),
        },
        HostEvent::SessionCreated { .. } => "sessionCreated" ~ HostEvent::SessionCreated {
            session_id: "s1".into(),
            header: header_sample(),
        },
        HostEvent::SessionDisposed { .. } => "sessionDisposed" ~ HostEvent::SessionDisposed {
            session_id: "s1".into(),
        },
        HostEvent::Error { .. } => "error" ~ HostEvent::Error {
            message: "gateway/internal".into(),
        },
    ]
}

wire_surface! {
    /// The §D.1 `StreamKind` vocabulary (what a `StreamOpen` asks for).
    table: STREAM_KINDS,
    /// Exhaustive wire-tag match for [`StreamKind`] (compile-time gate).
    tags: stream_kind_tag,
    /// One representative per [`STREAM_KINDS`] tag, in table order.
    samples: stream_kind_samples,
    ty: StreamKind,
    [
        StreamKind::FollowSession { .. } => "followSession" ~ StreamKind::FollowSession {
            session_id: "s1".into(),
            max_messages: Some(64),
        },
    ]
}

wire_surface! {
    /// The §D.1 `StreamFrame` payload vocabulary.
    table: STREAM_FRAMES,
    /// Exhaustive wire-tag match for [`StreamFrame`] (compile-time gate).
    tags: stream_frame_tag,
    /// One representative per [`STREAM_FRAMES`] tag, in table order.
    samples: frame_samples,
    ty: StreamFrame,
    [
        StreamFrame::Snapshot(_) => "snapshot" ~ StreamFrame::Snapshot(snapshot_sample()),
        StreamFrame::Entry { .. } => "entry" ~ StreamFrame::Entry {
            seq: 2,
            id: "e-2".into(),
            parent_id: Some("e-1".into()),
            timestamp: "2026-09-04T00:00:00Z".into(),
            event: JournalWireEvent::AgentTextDelta { s: "hi".into() },
        },
        StreamFrame::Projections(_) => "projections" ~ StreamFrame::Projections(ProjectionsFrame {
            session_id: "s1".into(),
            as_of_seq: 3,
            values: std::collections::BTreeMap::from([(
                "title".into(),
                serde_json::json!("v2 migration"),
            )]),
        }),
    ]
}

wire_surface! {
    /// The §D.1 stream-end reason vocabulary.
    table: STREAM_END_REASONS,
    /// Exhaustive wire-tag match for [`StreamEndReason`] (compile-time gate).
    tags: stream_end_tag,
    /// One representative per [`STREAM_END_REASONS`] tag, in table order.
    samples: stream_end_samples,
    ty: StreamEndReason,
    [
        StreamEndReason::Closed => "closed" ~ StreamEndReason::Closed,
        StreamEndReason::Cancelled => "cancelled" ~ StreamEndReason::Cancelled,
        StreamEndReason::Resync => "resync" ~ StreamEndReason::Resync,
        StreamEndReason::Failure { .. } => "failure" ~ StreamEndReason::Failure {
            code: crate::msg::CODE_RESYNC_REQUIRED.into(),
            message: "journal gap".into(),
        },
    ]
}

/// The §D.1 frame vocabulary: the `StreamKind` open frame, the three
/// `StreamFrame` payloads, and the four `StreamEndReason` arms. Mechanical
/// concatenation of the three generated tables — never hand-edited (the
/// former hand-maintained `FRAMES` const lacked `followSession` while
/// `StreamKind` declared FRAMES as its surface).
pub fn frames() -> Vec<&'static str> {
    let mut out = STREAM_KINDS.to_vec();
    out.extend_from_slice(STREAM_FRAMES);
    out.extend_from_slice(STREAM_END_REASONS);
    out
}

wire_surface! {
    /// `ClientCall` wire methods (§D.2, plus the retained v1 reads awaiting
    /// the C4 dual-protocol close-out).
    table: CLIENT_CALLS,
    /// Exhaustive wire-method match for [`ClientCall`] (compile-time gate).
    tags: client_call_tag,
    /// One representative per [`CLIENT_CALLS`] method, in table order.
    samples: client_call_samples,
    ty: ClientCall,
    [
        ClientCall::Initialize(_) => "initialize" ~ ClientCall::Initialize(Initialize {
            client_id: "test".into(),
            capabilities: vec![HookKind::Approve],
            sessions: vec![],
            protocol_epoch: crate::handshake::PROTOCOL_EPOCH,
        }),
        ClientCall::OpenSession { .. } => "openSession" ~ ClientCall::OpenSession {
            session_id: "s1".into(),
        },
        ClientCall::ListThreads => "listThreads" ~ ClientCall::ListThreads,
        ClientCall::ListModels => "listModels" ~ ClientCall::ListModels,
        ClientCall::ListCommands => "listCommands" ~ ClientCall::ListCommands,
        ClientCall::GetUsage { .. } => "getUsage" ~ ClientCall::GetUsage {
            session_id: "s1".into(),
        },
        ClientCall::GetCurrentModel { .. } => "getCurrentModel" ~ ClientCall::GetCurrentModel {
            session_id: "s1".into(),
        },
        ClientCall::ThreadInfo { .. } => "threadInfo" ~ ClientCall::ThreadInfo {
            session_id: "s1".into(),
        },
        ClientCall::TerminalAttach { .. } => "terminalAttach" ~ ClientCall::TerminalAttach {
            session: "s1".into(),
            cols: 80,
            rows: 24,
        },
        ClientCall::TerminalSnapshot { .. } => "terminalSnapshot" ~ ClientCall::TerminalSnapshot {
            terminal: "t1".into(),
        },
        ClientCall::ModelChat { .. } => "modelChat" ~ ClientCall::ModelChat {
            request_id: "r1".into(),
            model: "anthropic-main/claude-sonnet-4".into(),
            messages: serde_json::json!([]),
            tools: serde_json::json!([]),
        },
        ClientCall::CreateSession { .. } => "createSession" ~ ClientCall::CreateSession {
            cwd: Some("/proj".into()),
            project: Some("/proj".into()),
            initial_model: Some(ModelRef::new("DeepSeek-anthropic/deepseek-chat")),
            approval_mode: Some("workspace-write".into()),
            reasoning_effort: Some("high".into()),
        },
        ClientCall::Submit { .. } => "submit" ~ ClientCall::Submit {
            session_id: "s1".into(),
            text: "hello".into(),
            images: vec![ImageAttachment {
                data: vec![1, 2, 3],
                mime_type: "image/png".into(),
            }],
            origin_rpc: Some("rpc-echo-1".into()),
        },
        ClientCall::Steer { .. } => "steer" ~ ClientCall::Steer {
            session_id: "s1".into(),
            message_id: "m-1".into(),
            text: "left".into(),
            images: vec![],
            origin_rpc: None,
        },
        ClientCall::PageHistory { .. } => "pageHistory" ~ ClientCall::PageHistory {
            session_id: "s1".into(),
            through_seq: -1,
            before_seq: Some(40),
            max_messages: Some(32),
        },
        ClientCall::GetConversationInfo { .. } => "getConversationInfo" ~ ClientCall::GetConversationInfo {
            session_id: "s1".into(),
        },
        ClientCall::CancelDelivery { .. } => "cancelDelivery" ~ ClientCall::CancelDelivery {
            delivery_id: "dlv-s1-1".into(),
        },
    ]
}

wire_surface! {
    /// `ClientNote` wire methods (§D.3 keep set plus the compat entries
    /// awaiting the C4 dual-protocol close-out).
    table: CLIENT_NOTES,
    /// Exhaustive wire-method match for [`ClientNote`] (compile-time gate).
    tags: client_note_tag,
    /// One representative per [`CLIENT_NOTES`] method, in table order.
    samples: client_note_samples,
    ty: ClientNote,
    [
        ClientNote::CreateSession { .. } => "createSession" ~ ClientNote::CreateSession {
            session_id: "s1".into(),
            cwd: Some("/proj".into()),
        },
        ClientNote::DisposeSession { .. } => "disposeSession" ~ ClientNote::DisposeSession {
            session_id: "s1".into(),
        },
        ClientNote::DetachSession { .. } => "detachSession" ~ ClientNote::DetachSession {
            session_id: "s1".into(),
        },
        ClientNote::Submit { .. } => "submit" ~ ClientNote::Submit {
            session_id: "s1".into(),
            text: "hello".into(),
            images: vec![ImageAttachment {
                data: b"ab".to_vec(),
                mime_type: "image/png".into(),
            }],
            client_id: None,
        },
        ClientNote::Steer { .. } => "steer" ~ ClientNote::Steer {
            session_id: "s1".into(),
            client_id: "c1".into(),
            text: "mid".into(),
            images: vec![],
        },
        ClientNote::DropQueued { .. } => "dropQueued" ~ ClientNote::DropQueued {
            session_id: "s1".into(),
            client_id: "c1".into(),
        },
        ClientNote::CancelTurn { .. } => "cancelTurn" ~ ClientNote::CancelTurn {
            session_id: "s1".into(),
        },
        ClientNote::SetModel { .. } => "setModel" ~ ClientNote::SetModel {
            session_id: "s1".into(),
            id: "DeepSeek-anthropic/deepseek-chat".into(),
        },
        ClientNote::SetReasoningEffort { .. } => "setReasoningEffort" ~ ClientNote::SetReasoningEffort {
            session_id: "s1".into(),
            effort: "high".into(),
        },
        ClientNote::SetApprovalMode { .. } => "setApprovalMode" ~ ClientNote::SetApprovalMode {
            session_id: "s1".into(),
            mode: "auto-edit".into(),
        },
        ClientNote::SetCwd { .. } => "setCwd" ~ ClientNote::SetCwd {
            session_id: "s1".into(),
            cwd: "/new".into(),
        },
        ClientNote::SetPlanMode { .. } => "setPlanMode" ~ ClientNote::SetPlanMode {
            session_id: "s1".into(),
            enabled: true,
        },
        ClientNote::PlanSeedExecution { .. } => "planSeedExecution" ~ ClientNote::PlanSeedExecution {
            session_id: "s1".into(),
            plan_file: "/plan.md".into(),
        },
        ClientNote::Compact { .. } => "compact" ~ ClientNote::Compact {
            session_id: "s1".into(),
            instructions: None,
        },
        ClientNote::Goal { .. } => "goal" ~ ClientNote::Goal {
            session_id: "s1".into(),
            action: "create".into(),
            objective: Some("ship".into()),
            budget: Some(10),
            max_rounds: None,
        },
        ClientNote::StopBackgroundTask { .. } => "stopBackgroundTask" ~ ClientNote::StopBackgroundTask {
            session_id: "s1".into(),
            task_id: "b1".into(),
        },
        ClientNote::ArchiveThread { .. } => "archiveThread" ~ ClientNote::ArchiveThread {
            session_id: "s1".into(),
            archived: true,
        },
        ClientNote::PinThread { .. } => "pinThread" ~ ClientNote::PinThread {
            session_id: "s1".into(),
            pinned: true,
        },
        ClientNote::FocusThread { .. } => "focusThread" ~ ClientNote::FocusThread {
            session_id: Some("s1".into()),
        },
        ClientNote::TerminalInput { .. } => "terminalInput" ~ ClientNote::TerminalInput {
            terminal: "t1".into(),
            bytes: b"x".to_vec(),
        },
        ClientNote::TerminalResize { .. } => "terminalResize" ~ ClientNote::TerminalResize {
            terminal: "t1".into(),
            cols: 80,
            rows: 24,
        },
        ClientNote::CancelModelChat { .. } => "cancelModelChat" ~ ClientNote::CancelModelChat {
            request_id: "r1".into(),
        },
        ClientNote::Shutdown => "shutdown" ~ ClientNote::Shutdown,
        ClientNote::AppendUserMessage { .. } => "appendUserMessage" ~ ClientNote::AppendUserMessage {
            session_id: "s1".into(),
            text: "queued".into(),
            images: vec![],
        },
        ClientNote::AppendUiNote { .. } => "appendUiNote" ~ ClientNote::AppendUiNote {
            session_id: "s1".into(),
            kind: "notice".into(),
            data: serde_json::json!({"text": "n"}),
        },
    ]
}

wire_surface! {
    /// `ServerCall` wire methods (§D.4: waterfall trio + directed capability
    /// calls).
    table: SERVER_CALLS,
    /// Exhaustive wire-method match for [`ServerCall`] (compile-time gate).
    tags: server_call_tag,
    /// One representative per [`SERVER_CALLS`] method, in table order.
    samples: server_call_samples,
    ty: ServerCall,
    [
        ServerCall::Approve { .. } => "approve" ~ ServerCall::Approve {
            delivery_id: "dlv-s1-1".into(),
            session_id: "s1".into(),
            auth_id: "a1".into(),
            tool_name: "Bash".into(),
            summary: "ls".into(),
            input: serde_json::json!({"command": "ls"}),
        },
        ServerCall::PlanVerdict { .. } => "planVerdict" ~ ServerCall::PlanVerdict {
            delivery_id: "dlv-s1-2".into(),
            session_id: "s1".into(),
            plan_file: "/p.md".into(),
            title: "P".into(),
            content: Some("# P".into()),
        },
        ServerCall::AskUserQuestion { .. } => "askUserQuestion" ~ ServerCall::AskUserQuestion {
            delivery_id: "dlv-s1-3".into(),
            session_id: "s1".into(),
            auth_id: "a2".into(),
            input: serde_json::json!({}),
        },
        ServerCall::BrowserOp { .. } => "browserOp" ~ ServerCall::BrowserOp {
            session_id: "s1".into(),
            op: serde_json::json!({"op": "navigate"}),
        },
        ServerCall::ClipboardRead { .. } => "clipboardRead" ~ ServerCall::ClipboardRead {
            session_id: "s1".into(),
        },
        ServerCall::OpenExternal { .. } => "openExternal" ~ ServerCall::OpenExternal {
            session_id: "s1".into(),
            url: "https://x".into(),
        },
    ]
}

wire_surface! {
    /// The retained `ServerNote` method vocabulary (post-T10 §D.6 removal
    /// pass): owner control (`ready` / `sessionCreated` / `sessionDisposed`),
    /// the transitional registry-push list channel (`threadsUpdated` /
    /// `models` / `commands`), the server-originated `error`, and the
    /// `model_chat` side-stream (`modelText` / `modelThinking` /
    /// `modelToolCall` / `modelChatDone`, §K.6). The C4 close-out removes
    /// the transitional entries together with their enum variants — one list
    /// edit, compiler-checked.
    table: SERVER_NOTES,
    /// Exhaustive wire-method match for [`ServerNote`] (compile-time gate).
    tags: server_note_tag,
    /// One representative per [`SERVER_NOTES`] method, in table order.
    samples: server_note_samples,
    ty: ServerNote,
    [
        ServerNote::Ready => "ready" ~ ServerNote::Ready,
        ServerNote::SessionCreated { .. } => "sessionCreated" ~ ServerNote::SessionCreated {
            session_id: "s1".into(),
        },
        ServerNote::SessionDisposed { .. } => "sessionDisposed" ~ ServerNote::SessionDisposed {
            session_id: "s1".into(),
        },
        ServerNote::ThreadsUpdated { .. } => "threadsUpdated" ~ ServerNote::ThreadsUpdated {
            threads: vec![thread_stub()],
        },
        ServerNote::Models { .. } => "models" ~ ServerNote::Models {
            models: vec![model_stub()],
        },
        ServerNote::Commands { .. } => "commands" ~ ServerNote::Commands {
            commands: serde_json::json!([]),
        },
        ServerNote::ModelText { .. } => "modelText" ~ ServerNote::ModelText {
            request_id: "r".into(),
            text: "t".into(),
        },
        ServerNote::ModelThinking { .. } => "modelThinking" ~ ServerNote::ModelThinking {
            request_id: "r".into(),
            text: "t".into(),
        },
        ServerNote::ModelToolCall { .. } => "modelToolCall" ~ ServerNote::ModelToolCall {
            request_id: "r".into(),
            id: "tc".into(),
            name: "Bash".into(),
            input: serde_json::json!({}),
        },
        ServerNote::ModelChatDone { .. } => "modelChatDone" ~ ServerNote::ModelChatDone {
            request_id: "r".into(),
            stop: None,
            error: None,
        },
        ServerNote::Error { .. } => "error" ~ ServerNote::Error {
            session_id: None,
            message: "boom".into(),
        },
    ]
}

fn model_stub() -> ModelInfo {
    ModelInfo {
        id: "deepseek-chat".into(),
        name: "DeepSeek Chat".into(),
        provider: "DeepSeek-anthropic".into(),
        provider_name: None,
        api: "anthropic".into(),
        context_window: 131_072,
        max_tokens: None,
    }
}

fn thread_stub() -> ThreadListItem {
    ThreadListItem {
        id: "s1".into(),
        title: "v2 migration".into(),
        updated_at: 1_756_947_200,
        running: false,
        unread: false,
        errored: false,
        pending_auth: false,
        pending_plan: false,
        background_work: false,
        model_id: "DeepSeek-anthropic/deepseek-chat".into(),
        pinned: false,
        archived: false,
        parent_id: None,
        depth: 0,
    }
}

/// `StreamKind` sample for the scripted conversation (§D.1).
pub fn stream_kind_follow(session_id: &str) -> StreamKind {
    StreamKind::FollowSession {
        session_id: session_id.into(),
        max_messages: Some(64),
    }
}

/// The scripted session's header.
pub fn header_sample() -> crate::journal::ThreadHeader {
    crate::journal::ThreadHeader {
        id: "s1".into(),
        cwd: "/proj".into(),
        parent_session: None,
        metadata: None,
        created_at: "2026-09-04T00:00:00Z".into(),
    }
}

/// The scripted session's opening snapshot (one `message` record + a
/// projection baseline covering the §E.2 key set; L6 client reads, never
/// folds).
pub fn snapshot_sample() -> SessionSnapshot {
    let mut projections = std::collections::BTreeMap::new();
    for key in PROJECTION_KEYS {
        projections.insert((*key).to_string(), serde_json::json!(key));
    }
    SessionSnapshot {
        session_id: "s1".into(),
        header: header_sample(),
        cursor: 1,
        records: vec![JournalWireEntry {
            seq: 0,
            id: "e-0".into(),
            parent_id: None,
            timestamp: "2026-09-04T00:00:00Z".into(),
            event: JournalWireEvent::Message {
                role: "user".into(),
                content: vec![serde_json::json!({"type": "text", "text": "hello"})],
                usage: Some(UsagePayload {
                    input: 10,
                    output: 2,
                    cache_read: 0,
                    cache_write: 0,
                    reasoning: 0,
                }),
                origin_rpc: Some("rpc-echo-1".into()),
            },
        }],
        has_more: false,
        projections,
        projections_as_of_seq: 0,
    }
}

/// The scripted conversation: the frame samples as `StreamItem`s, one entry
/// frame per declared journal event (dense seq), and one `StreamEnd` per
/// declared reason — all on the real §D.1 envelope. The coverage harness
/// walks it exactly as a client would consume a live follow stream.
pub fn scripted_session() -> Vec<FromServer> {
    use crate::journal::StreamId;
    let stream_1 = StreamId::new("stream-1");
    let mut out = Vec::new();
    for frame in frame_samples() {
        out.push(FromServer::StreamItem {
            stream_id: stream_1.clone(),
            frame,
        });
    }
    // Then every journal entry, one frame each, dense continuing seq.
    for (i, event) in journal_samples().into_iter().enumerate() {
        out.push(FromServer::StreamItem {
            stream_id: stream_1.clone(),
            frame: StreamFrame::Entry {
                seq: (10 + i) as u64,
                id: format!("e-{}", 10 + i),
                parent_id: Some(format!("e-{}", 9 + i)),
                timestamp: "2026-09-04T00:00:00Z".into(),
                event,
            },
        });
    }
    // Stream lifecycle endings (§D.1 StreamEnd) — one per declared reason,
    // each on its own stream id so the emit-coverage walk sees every
    // end-reason name in a single scripted session.
    let endings = [
        (stream_1, StreamEndReason::Closed),
        (StreamId::new("stream-2"), StreamEndReason::Cancelled),
        (StreamId::new("stream-3"), StreamEndReason::Resync),
        (
            StreamId::new("stream-4"),
            StreamEndReason::Failure {
                code: "gateway/internal".into(),
                message: "scripted failure".into(),
            },
        ),
    ];
    for (stream, reason) in endings {
        out.push(FromServer::StreamEnd {
            stream_id: stream,
            reason,
        });
    }
    out
}

/// The scripted `HostEvent` sequence on the real production envelope
/// (`FromServer::Host`). The former version wrapped host events in
/// `FromServer::Response` outcome payloads — a fake envelope no production
/// sender ever used, which let the emit-coverage proof pass while the real
/// `Host` variant had zero round-trip coverage.
pub fn scripted_host_events() -> Vec<FromServer> {
    host_samples()
        .into_iter()
        .map(|host| FromServer::Host { host })
        .collect()
}

/// The scripted `FromClient` opening: the real §D.1 `StreamOpen` envelope
/// carrying a `FollowSession` kind (T4).
pub fn scripted_stream_open() -> FromClient {
    FromClient::StreamOpen {
        stream_id: crate::journal::StreamId::new("stream-1"),
        stream_kind: stream_kind_follow("s1"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn projection_key_table_has_exactly_20_entries() {
        assert_eq!(PROJECTION_KEYS.len(), 20);
    }

    /// The generated tag match agrees with the generated table on every
    /// generated sample — the three artifacts of one list stay in lockstep
    /// (serde agreement is asserted by tests/surface_coverage.rs).
    #[test]
    fn tag_functions_agree_with_tables() {
        for (tag, sample) in JOURNAL_ENTRIES.iter().zip(journal_samples()) {
            assert_eq!(journal_wire_tag(&sample), *tag);
        }
        for (tag, sample) in HOST_EVENTS.iter().zip(host_samples()) {
            assert_eq!(host_wire_tag(&sample), *tag);
        }
        for (tag, sample) in STREAM_KINDS.iter().zip(stream_kind_samples()) {
            assert_eq!(stream_kind_tag(&sample), *tag);
        }
        for (tag, sample) in STREAM_FRAMES.iter().zip(frame_samples()) {
            assert_eq!(stream_frame_tag(&sample), *tag);
        }
        for (tag, sample) in STREAM_END_REASONS.iter().zip(stream_end_samples()) {
            assert_eq!(stream_end_tag(&sample), *tag);
        }
        for (tag, sample) in CLIENT_CALLS.iter().zip(client_call_samples()) {
            assert_eq!(client_call_tag(&sample), *tag);
        }
        for (tag, sample) in CLIENT_NOTES.iter().zip(client_note_samples()) {
            assert_eq!(client_note_tag(&sample), *tag);
        }
        for (tag, sample) in SERVER_CALLS.iter().zip(server_call_samples()) {
            assert_eq!(server_call_tag(&sample), *tag);
        }
        for (tag, sample) in SERVER_NOTES.iter().zip(server_note_samples()) {
            assert_eq!(server_note_tag(&sample), *tag);
        }
    }

    #[test]
    fn frames_is_the_mechanical_concatenation() {
        let mut want = STREAM_KINDS.to_vec();
        want.extend_from_slice(STREAM_FRAMES);
        want.extend_from_slice(STREAM_END_REASONS);
        assert_eq!(frames(), want);
        assert_eq!(frames().len(), 8);
    }

    #[test]
    fn tables_have_no_duplicate_names() {
        let tables: Vec<Vec<&str>> = vec![
            JOURNAL_ENTRIES.to_vec(),
            PROJECTION_KEYS.to_vec(),
            HOST_EVENTS.to_vec(),
            frames(),
            CLIENT_CALLS.to_vec(),
            CLIENT_NOTES.to_vec(),
            SERVER_CALLS.to_vec(),
            SERVER_NOTES.to_vec(),
        ];
        for table in tables {
            let mut sorted = table.clone();
            sorted.sort_unstable();
            let n = sorted.len();
            sorted.dedup();
            assert_eq!(sorted.len(), n, "duplicate name in table {table:?}");
        }
    }
}
