[package]
name = "manox-protocol"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
manox-journal.workspace = true
serde.workspace = true
serde_json.workspace = true
async-channel.workspace = true
parking_lot.workspace = true

[dev-dependencies]
serde_json.workspace = true
proptest = "1"
